Claims academic year filter
DFE-Digital/itt-mentor-services pull request #1024
Opened 2024-09-13 11:53 UTC by Kizr

## Context

We want to be able to see which Academic year each claim was made against.

We also want to be able to filter claims by academic year in the support console.

## Changes proposed in this pull request

- [x] Delegate `:name` to `AcademicYear` from a claim
- [x] Update the claim show page for support to display the academic year
- [x] Update the claim card for the index page to display the academic year
- [x] Add a new `order_by_date` scope to the `AcademicYear` to ensure correct order for filter display
- [x] Add an academic year condition to the claims query
- [x] Add academic_year_ids to the claims filter form
- [x] Wrote a system spec to cover the functionality

## Guidance to review

- Log in as Colin
- Navigate to the claims in the navigation
- Filter claims by the current academic year (2024 to 2025) 
- All claims should be displayed
- Clear all filters
- Filter claims by the next academic year (2025 to 2026)
- No claims should be displayed
- Clear the filter using the 2025 to 2026 pill
- All claims should be displayed

## Link to Trello card

[How we identify which claims are associated with each academic year / claim window (support console)](https://trello.com/c/a3HYWhwk/793-how-we-identify-which-claims-are-associated-with-each-academic-year-claim-window-support-console)

## Screenshots

![image](https://github.com/user-attachments/assets/853d4162-47d2-4d5f-9710-71e87222409f)
![image](https://github.com/user-attachments/assets/c5b6e0ed-3330-4e5f-b0bd-8289c6aec8df)

2024-09-13 12:23 UTC, Nitemaeric approved these changes

2024-09-13 12:23 UTC, Nitemaeric commented on app/assets/stylesheets/components/claim/card.scss
> +    .claim-card__body__details {
👍

2024-09-13 12:23 UTC, Nitemaeric commented on app/queries/claims/claims_query.rb
> +  end
I believe this works too. I'm not sure which is objectively better though.

A join is great with lesser records, but a subquery also works well.

```suggestion
  def academic_year_condition(scope)
    return scope if params[:academic_year_ids].blank?

    scope.joins(:academic_year).where(academic_years: { id: params[:academic_year_ids] })
  end
```

2024-09-17 15:26 UTC, Nitemaeric requested changes
I've been given some design feedback to hold this off and make tweaks before we ship this.

2024-09-17 15:29 UTC, Nitemaeric commented
Additional requirements:

- Only show Academic Years from the list of Claim Windows.
  - `AcademicYear.where(id: Claims::ClaimWindow.select(:academic_year_id)`
- Only show the Academic Year filter if there is more than 1 option.
- Add a read-only Academic Year field to the Claim creation check page under the School name.
- Add a read-only Academic Year field to the Claim details page under the School name on the User's side too.

2024-09-19 12:55 UTC, Kizr commented
> @Kizr just FYI, I think you've got your commit messages the wrong way around here. These commits do a different thing compared to their commit messages.
> 
> * [Select academic years from claim windows](https://github.com/DFE-Digital/itt-mentor-services/pull/1024/commits/17536b95c09dcab1dacd8b41f1c178aba7e9918c) ([17536b9](https://github.com/DFE-Digital/itt-mentor-services/commit/17536b95c09dcab1dacd8b41f1c178aba7e9918c))
> * [Only show academic year filter when more than one academic years exist](https://github.com/DFE-Digital/itt-mentor-services/pull/1024/commits/735a14e8ef63a951b6f3521f7a7a8b59ed99a4c0) ([735a14e](https://github.com/DFE-Digital/itt-mentor-services/commit/735a14e8ef63a951b6f3521f7a7a8b59ed99a4c0))
> 
> They need swapping around 😄

I have no idea how I managed to do that 😕

2024-09-19 16:10 UTC, ollietreend approved these changes

2024-09-20 09:40 UTC, Nitemaeric approved these changes
Nice one! Thanks!

Product would like to review this one in a review app before we merge though.

2024-09-20 09:40 UTC, Nitemaeric commented on app/views/claims/support/claims/_filter.html.erb
> +          <% if @academic_years.many? %>
TIL `#many?` ❤️

2024-09-25 14:01 UTC, merged