School user → Mentor index and add mentor wizard UI changes
DFE-Digital/itt-mentor-services pull request #1043
Opened 2024-09-18 13:58 UTC by dp-daly

## Context

Wayfinder changes in line with updated designs.

## Changes proposed in this pull request

**Index**
- Change H1: Mentors at your school
- Add intro text: Add mentors to be able to assign them to your placements.

**Check your answers**
- Remove H1 caption
- Change H1: Confirm mentor details
- Add intro text: Once added, you will be able to assign them to placements.
- Add H2: Mentor
- Change inset text: Mentor data is stored in line with the [Department for Education's (DfE) privacy notice (opens in new tab)](https://bat-school-placements-18b07385d8a1.herokuapp.com/school-users/v3/add-mentor-check). I confirm that I have read, understood and accept how DfE uses mentor information as part of the Manage school placements service.
- The ‘privacy notice’ link should still have the same destination as before. However, it should now open in a new tab (which it didn’t previously).
- Change button text: Confirm and add mentor

## Guidance to review

- Log in as school user.
- Click 'Mentors' tab.
- Review the index header - it should now read "Confirm mentor details" and there should be no caption.
- Add a mentor using dummy details (trn: 1234565, dob: 09/1/1991).
- Review the 'Check your answers' page, which should now reflect the changes outlined above. Including a new header: 'Confirm mentor details'.
- Click the privacy notice link to make sure it opens in a new tab.
- Complete the process by pressing 'Confirm and add mentor'.

## Link to Trello card

https://trello.com/c/E2Qf4C7G/798-school-user-%E2%86%92-mentors

## Screenshots

<img width="678" alt="Screenshot 2024-09-18 at 14 58 04" src="https://github.com/user-attachments/assets/adc227ea-be89-42f1-88e3-5e5c97219d55">

<img width="675" alt="Screenshot 2024-09-18 at 14 58 20" src="https://github.com/user-attachments/assets/2b1338ea-9aea-4cc4-bade-ee9f13c0fccb">

2024-09-19 13:10 UTC, Kizr requested changes

2024-09-19 13:10 UTC, Kizr commented on app/views/placements/wizards/add_mentor_wizard/_check_your_answers_step.html.erb
> +                    t(".privacy_notice"), placements_privacy_path, target: "_blank", new_tab: true, no_visited_state: true
```suggestion
                    t(".privacy_notice"), placements_privacy_path, new_tab: true, no_visited_state: true
```

The `new_tab` argument sets `target="_blank"` for us automatically, but unfortunately this isn't working on the review app, it looks like the `embedded_link_text` is eating our `target="_blank"` 🤔

2024-09-20 08:20 UTC, Kizr submitted a review, later dismissed

2024-09-20 08:20 UTC, Kizr commented on app/helpers/placements/translations_helper.rb
> +    sanitize translations, tags: %w[a], attributes: %w[href target]
```suggestion
    sanitize translations, tags: %w[a], attributes: %w[href target class]
```

We've chosen to be explicit here, would it be suitable to add the `class` attribute to this list to decrease cognitive load?

2024-09-20 08:20 UTC, Kizr commented on app/views/placements/wizards/add_mentor_wizard/_check_your_answers_step.html.erb
> +                    t(".privacy_notice"), placements_privacy_path, target: "_blank", new_tab: true, no_visited_state: true
Is the `target="_blank"` needed here?

2024-09-20 08:20 UTC, Kizr commented on config/environments/development.rb
> +  config.action_controller.raise_on_missing_callback_actions = false
Did we agree to remove this from this PR to resolve properly?

2024-09-20 08:20 UTC, Kizr commented on spec/system/placements/support/schools/mentors/support_user_adds_a_mentor_spec.rb
> +  def then_i_see_check_page_for(mentor, _school)
Is `_school` needed here?

2024-09-24 09:17 UTC, ollietreend submitted a review, later dismissed

2024-09-27 13:07 UTC, closed without merging

2024-09-27 13:07 UTC, ollietreend commented
I'm closing this PR as it has been combined into the overall way finding PR #1071.