UI changes to school user -> providers
DFE-Digital/itt-mentor-services pull request #1049
Opened 2024-09-19 16:34 UTC by dp-daly

## Context

For school users, “Partner providers” is being renamed to simply “Providers”.

## Changes proposed in this pull request

**Index**
- Change H1: Providers you work with
- Add intro text: Add providers to be able to assign them to your placements.
- Change button text: Add provider
- Change navbar link from “Partner providers” to “Providers”

**Add provider → Add a provider**
- Change H1 caption: Provider details

**- Add provider → Confirm provider details**
- Remove H1 caption
- Change H1 text: Confirm provider details
- Add intro text: Adding them means you will be able to assign them to your placements. We will send them an email to let them know you have added them.
- Add H2: Provider
- Consolidate to show provider details in one summary list.

**Provider details**
- Change delete link: Delete provider

**Delete provider**
- Change H1: Are you sure you want to delete this provider?
- Split paragraph into two: You will no longer be able to assign this provider to placements. /They will remain assigned to current placements unless you remove them. 
- Change warning text: We will send an email to [provider name] to let them know they are no longer one of your providers. It is your responsibility to confirm with them whether they should fulfil existing assigned placements.
- Change button text: Delete provider

## Guidance to review

- Log in as a school user.
- Navigate to the 'Providers' tab.
- Complete the journey of adding a provider with reference to changes outlined above.
- Once completed, click into a provider from the index page.
- Review the show page.

## Link to Trello card

https://trello.com/c/6CmZ9zJg/797-school-user-%E2%86%92-providers

2024-09-20 08:36 UTC, Kizr reviewed
Please could you add some screenshots of the changes?

2024-09-20 08:36 UTC, Kizr commented on app/views/shared/organisations/_organisation_details.html.erb
> +    <% summary_list.with_row do |row| %>
```suggestion
  <% summary_list.with_row do |row| %>
```

2024-09-20 08:36 UTC, Kizr commented on config/environments/development.rb
> +  config.action_controller.raise_on_missing_callback_actions = false
Should this be included in this PR?

2024-09-24 11:19 UTC, ollietreend requested changes

2024-09-24 11:19 UTC, ollietreend commented on app/views/shared/organisations/_organisation_details.html.erb
This makes me nervous because it's a change to a shared partial, which is [used in various places](https://github.com/search?q=repo:DFE-Digital/itt-mentor-services+%22shared/organisations/organisation_details%22+path:/%5Eapp%5C/views%5C//&type=code) across both services.

For example, it has made the following change over in the Claims service:

| Before | After |
| --- | --- |
| ![Claims before partial changes](https://github.com/user-attachments/assets/33628210-9719-4346-a302-bf077a423115) | ![Claims after partial changes](https://github.com/user-attachments/assets/6979c9ba-f28b-4ec9-816c-2ff6b294bbc4) |

To avoid making unexpected changes elsewhere in the app, I think we'll probably need to revert the changes made to this file.

To apply the required content changes specifically to the 'show' and 'check your answers' pages, we probably have a couple of options:

1. **Don't use a partial:** Rather than rendering a partial, just add the HTML directly into the view files where the org details need to be shown.
2. **Create a new partial:** Create a new partial which is specifically scoped to the Placements service, so it doesn't results in inadvertent changes over in Claims. And then use this partial instead of the 'shared' one.

**Option 2** is probably the best long term approach, because it'll avoid us needing to duplicate HTML code around the place when other pages need to display org details in the same way.

2024-09-24 11:26 UTC, ollietreend commented on app/views/shared/organisations/_organisation_details.html.erb
Path for Placements partial:

```
app/views/placements/organisations/_organisation_details.html.erb
```

2024-09-25 09:55 UTC, dp-daly commented on app/views/shared/organisations/_organisation_details.html.erb
Thank you - all updated. I've only just spotted the suggested path for the claims partial. Currently it lives in the below path but very happy to move if needed:
`app/views/claims/schools/_organisation_details.html.erb`

One other thing to flag is that this change leads to a bit of duplication of school address under schools user -> organisation details tab, which I think is just a design vestige we might want to align with this change.

2024-09-27 13:07 UTC, ollietreend commented
I'm closing this PR as it has been combined into the overall way finding PR #1071.

2024-09-27 13:07 UTC, closed without merging