Refactor footer helper to accommodate both services
DFE-Digital/itt-mentor-services pull request #401
Opened 2024-03-22 14:21 UTC by CatalinVoineag

## Context

## Changes proposed in this pull request

## Guidance to review

## Link to Trello card

## Things to check

- [ ] If the code removes any existing feature flags, a data migration has also been added to delete the entry from the database
- [ ] This code does not rely on migrations in the same Pull Request
- [ ] If this code includes a migration adding or changing columns, it also backfills existing records for consistency
- [ ] If this code adds a column to the DB, decide whether it needs to be in analytics yml file or analytics blocklist
- [ ] API release notes have been updated if necessary
- [ ] If it adds a significant user-facing change, is it documented in the [CHANGELOG](CHANGELOG.md)?
- [ ] Required environment variables have been updated or [added to the Azure KeyVault](/docs/environment-variables.md#deploy-pipeline)

## Screenshots

2024-03-22 14:24 UTC, CatalinVoineag commented
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor footer_helper](https://trello.com/c/ffUATsPW/307-refactor-footerhelper)

2024-03-22 15:45 UTC, Nitemaeric commented on app/helpers/footer_helper.rb
> +    end
Let's avoid using an `else` statement. If `current_service` is not either `:claims` or `:placements`, we want to immediately be able to see that.

```suggestion
    {
      claims: claims_footer_meta_items,
      placements: placements_footer_meta_items
    }.fetch current_service
```

2024-03-25 09:04 UTC, Kizr requested changes
Please could we add a test for `footer_meta_items`? Given this app serves two purposes it would give us more confidence that we haven't mistakenly broken the part we can't see.

2024-03-25 09:36 UTC, Kizr approved these changes
Awesome, thank you!

2024-03-25 09:40 UTC, merged