UI changes to placements show page
DFE-Digital/itt-mentor-services pull request #969
Opened 2024-08-29 16:42 UTC by dp-daly

## Context

In line with UI design changes, academic year and expected dates offer the school user the ability to provide more period-specific information about the placements they are listing.

## Changes proposed in this pull request

- Add the 'Academic year' field to the placement show page
- Add the 'Expected date' field to the placement show page
- Add the change link to the edit placement wizard for the expected date field

## Guidance to review

- Log in as a Anne
- Click 'Add a placement'
- Create a placement, including selecting a term on the term step
- Return to the index 
- Click into the newly created placement
- Check that the relevant academic year shows
- Check the show page includes the name of the chosen term
- Repeat this but choose all three terms
- Check the show page includes 'Any time in the academic year'
- Repeat this but choose 'Any time in the academic year'
- Check the show page includes 'Any time in the academic year'

## Link to Trello card

https://trello.com/c/wIDHzSps/711-school-update-placements-show-with-academic-year-and-placement-date

## Screenshots

<img width="811" alt="Screenshot 2024-08-29 at 17 36 37" src="https://github.com/user-attachments/assets/273156f2-e3ac-411b-8c63-fbbf9af2ec26">
<img width="793" alt="Screenshot 2024-08-29 at 17 36 18" src="https://github.com/user-attachments/assets/ef109da4-9dcb-4850-99f8-430be87496f9">

2024-08-30 08:13 UTC, JamieCleare2525 commented on app/decorators/placement_decorator.rb
> +  end
This will conflict with @Kizr's https://github.com/DFE-Digital/itt-mentor-services/pull/968/files. Good idea to chat with him.

2024-08-30 10:19 UTC, JamieCleare2525 commented on app/views/placements/schools/placements/_details.html.erb
> +    <% end %>
Something has gone wrong with your rebase. You'll need to remove this duplicated code.

2024-08-30 10:19 UTC, JamieCleare2525 requested changes
Rebase issue has caused duplicated code.

2024-08-30 10:22 UTC, JamieCleare2525 commented on app/views/placements/schools/placements/_details.html.erb
>        <% row.with_key(text: t(".attributes.placements.year_group")) %>
Year group should be above the academic year row.

2024-08-30 10:43 UTC, JamieCleare2525 approved these changes

2024-09-02 11:43 UTC, ollietreend approved these changes
Looks good to me. Thanks for rebasing & squashing!

2024-09-02 11:55 UTC, merged